### ISSUE TITLE
Expands work wrongly in LESS files

### ISSUE THREAD

**Issue by pstjvn** [rmariuzzo/cloud9-emmet-ext#2]
I have a less file in cloud9, I type 'bgc' and activate the extension, however instead of expanding to 'backgruond-color: #fff;' it expands to '<bgc></bgc>'

I am not sure if this problem is with emmet or with the extension however.

**Comment by rmariuzzo** [comment]
Thanks for reporting it. At this moment I have only tried with HTML files, no LESS or CSS files. I think I have to _hook it_ properly to make it work for CSS/LESS files. I will be checking in a few hours.

Can you also confirm that this behavior is happening for CSS files.

**Comment by rmariuzzo** [comment]
@pstjvn, I just made some test expanding the abbreviation `bgc` in two files: a CSS and a LESS file. 

For the CSS file, the extension correctly expanded the abbreviation to:

`background-color: #fff;`

But for the LESS file, the expansion was:

`<bgc></bgc>`

It is a bug of the extension not of Emmet. It looks like Emmet couldn't autodetect the context of a LESS falling back to HTML, so I have to make the extension detect LESS files as CSS files for Emmet.

I will check in a while.

**Comment by pstjvn** [comment]
Awesome, and it is also auto updated in the IDE, so right after your commit I was able to test it. 
Thanks.

**Comment by rmariuzzo** [comment]
Really? Which URL are you using in the extension manager?

**Comment by pstjvn** [comment]
https://raw.github.com/rmariuzzo/cloud9-emmet-ext/master/cloud9-emmet-ext.js
Maybe it loads it every time I start the IDE? (i.e. Ctrl+r)

**Comment by rmariuzzo** [comment]
Nice! I was just wondering, since dasy ago I updated the readme file to point out that it is preferable that location to install the extension instead of cloning/forking my repo then importing it into C9.

Thanks again for your time.
