### ISSUE TITLE
html:5 abbreviation issue

### ISSUE THREAD

**Issue by YoussF** [rmariuzzo/cloud9-emmet-ext#3]
Hello,

It looks like the standard html:5 abbreviation does not expand properly. It expands like this :

&lt;html:5&gt;&lt;/html:5&gt;

Instead of like this :

&lt;!doctype html&gt;<br/>&lt;html lang=&quot;en&quot;&gt;<br/>&lt;head&gt;<br/>    &lt;meta charset=&quot;UTF-8&quot;&gt;<br/> &lt;title&gt;Document&lt;/title&gt;<br/>&lt;/head&gt;<br/>&lt;body&gt;<br/> <br/>&lt;/body&gt;<br/>&lt;/html&gt;

Thanks you for your support.

**Comment by rmariuzzo** [comment]
Thank you for reporting this. I will check as fast as I can. By the moment you can use the `!` alias. It will do the same as `html:5`. I will check if I can report that issue.

**Comment by YoussF** [comment]
Thanks you or you quick reply. But i don't know how to use  the <code>!</code> alias. Is it part of emmet ? if i try to expand <code>!</code> i get <code><!></!></code>

**Comment by rmariuzzo** [comment]
Yes, it is part of Emmet. Are you editing an HTML file or something else?
