### ISSUE TITLE
Under Tools the Extension Manager is Not There

### ISSUE THREAD

**Issue by JamesVanWaza** [rmariuzzo/cloud9-emmet-ext#5]
![screen shot 2014-09-29 at 6 35 02 pm](https://cloud.githubusercontent.com/assets/4000076/4450717/e61d2544-4828-11e4-99a6-c60ed099ee3a.png)

**Comment by BenBroide** [comment]
I have the same issue.

**Comment by JamesVanWaza** [comment]
Cloud9 was acquired by Amazon. No updates since then.
